"""empty message

Revision ID: 57a9d07eaf6e
Revises: 638532243372
Create Date: 2024-06-11 20:35:13.749143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9d07eaf6e'
down_revision: Union[str, None] = '638532243372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_info', sa.Column('source', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wine_info', 'source')
    # ### end Alembic commands ###
