"""empty message

Revision ID: e3f4a44cb1d4
Revises: 
Create Date: 2024-06-11 19:48:23.528248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f4a44cb1d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grape_variety', sa.String(length=128), nullable=True),
    sa.Column('appellation', sa.String(length=128), nullable=True),
    sa.Column('alcohol_content', sa.Float(), nullable=True),
    sa.Column('serving_temperature', sa.String(length=128), nullable=True),
    sa.Column('wine_type', sa.String(length=128), nullable=False),
    sa.Column('vivino_rating', sa.Float(), nullable=True),
    sa.Column('vivino_reviews', sa.Integer(), nullable=True),
    sa.Column('vivino_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('vivino_url')
    )
    op.create_table('award',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('critic', sa.String(length=128), nullable=False),
    sa.Column('score', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine_info')
    op.drop_table('award')
    op.drop_table('wine')
    # ### end Alembic commands ###
